baseURL = "https://jaigansa.github.io/tamilnux/"
languageCode = 'en-us'
title = 'Tamilnux'
theme = 'tamilnux'



[params]
  featuredImage = "/images/banner/thumb_wip.webp"
  authorName = "Jai Ganesh"
  socialLinks = ["https://twitter.com/yourhandle", "https://github.com/yourhandle"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[permalinks]
  tags = "/topics/:slug/"


[taxonomies]
  tag = "tags"
  category = "categories"
