baseURL = "https://jaigansa.github.io/tamilnux/"
languageCode = 'en-us'
title = 'Tamilnux'
theme = 'tamilnux'



[params]
  featuredImage = "/images/thumb/wip.webp"
  authorName = "Jai Ganesh"
  socialLinks = ["https://twitter.com/yourhandle", "https://github.com/yourhandle"]

[[module.mounts]]
  source = 'static'
  target = 'static'
    
[permalinks]
  tags = "/topics/:slug/"


[taxonomies]
  tag = "tags"
  category = "categories"
