baseURL = "https://jaigansa.github.io/jaigarage/"
languageCode = 'en-us'
title = 'Jaigarage'
theme = 'jaigarage'



[[module.mounts]]
  source = 'static'
  target = 'static'
    
[permalinks]
  tags = "/topics/:slug/"


[taxonomies]
  tag = "tags"
  category = "categories"




[privacy]
  [privacy.instagram]
    disable = false
    simple = true

