baseURL = 'https://jaigansa.github.io/tamilnux/'
languageCode = 'en-us'
title = 'Tamilnux'
theme = 'tamilnux'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 30


[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"