baseURL = 'https://tamilnux.in/'
languageCode = 'en-US'
title = 'Tamilnux Theme'

[params]
  featured_image = "images/wip_banner.webp"
  author_name = "Jai Ganesh"
  social_links = ["https://twitter.com/jaigansa"]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 30


[[menus.main]]
name = 'Installs'
pageRef = '/installs'
weight = 40

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 50


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
